[project]
name = "project-streamlit"
version = "0.1.0"
description = "GenAI Code and Test Case Generator"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "streamlit>=1.49.1",
    "transformers>=4.55.0",
    "torch>=2.6.0",
    "accelerate>=1.6.0",
    "huggingface-hub>=0.34.0",
]